pipeline{

   //任何一个代理可用的机器就立即执行代码构建
   agent any
   //定义环境信息
   //定义流水线的加工流程

   stages{
   //1.编译
   stage('代码编译'){
      steps{
      echo '编译......'
      }
   }

   //2.测试
   stage('代码测试'){
      steps{
      echo '测试......'
      sh  'pwd && ls -l'
      echo '$SSH_CONNECTION'
      }
   }

   //3.打包
   stage('代码打包'){
      steps{
       echo '打包......'
       }
   }

   //4.部署
   stage('代码部署'){
      steps{
        echo '部署......'
        }
   }

   }
}
